const data = [
    {
        title: 'Mens Unique Leather Band Dress Wrist Watch',
        description: 'Top of the line watch that you should buy for a lot right now',
        condition: 'great',
        price: 80,
        city: 'San Francisco',
        state: 'CA',
        category: 'Clothing & Accessories',
        status: 'active',
        owner: 'Shujian',
        date: '3 days ago'
    },
    {
        title: 'Overkill Nerf Guns with Ammo',
        description: 'Make your colleagues regret working within a 70 foot radius of you with these obnoxiously large nerf guns',
        condition: 'great',
        price: 2000,
        city: 'Tempe',
        state: 'AZ',
        category: 'Non Lethal Weaponry',
        photo: 'https://i.imgur.com/BE7rgvm.jpg',
        status: 'active',
        owner: 'Gulshan',
        date: '2 days ago'
    },
    {
        title: 'Kitchen Table',
        description: '36 inch x 48 inch kitchen table',
        condition: 'new',
        price: 70,
        city: 'San Francisco',
        state: 'CA',
        category: 'Furniture',
        photo: 'https://i.imgur.com/LOWD9u7.jpg',
        status: 'draft',
        owner: 'Kevin',
        date: 'Yesterday'
    },
    {
        title: 'Plant',
        description: 'It will give you some O2',
        condition: 'new',
        price: 20,
        city: 'San Francisco',
        state: 'CA',
        category: 'Misc',
        photo: 'https://i.imgur.com/qKVwxaQ.jpg',
        status: 'active',
        owner: 'Shujian',
        date: '3 days ago'
    },
    {
        title: 'iPhone',
        description: 'Please take my old iPhone 8',
        condition: 'used',
        price: 300,
        city: 'Tempe',
        state: 'AZ',
        category: 'Technology',
        photo: 'https://i.imgur.com/6ty0r2c.jpg',
        status: 'active',
        owner: 'Abhishek',
        date: 'Yesterday'
    },
    {
        title: 'Coffe Mug',
        description: 'Not sure why I dont just throw this away',
        condition: 'used',
        price: 3,
        city: 'Tempe',
        state: 'AZ',
        category: 'Misc',
        photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_1S1SNIhd9o-kc8YQ_jbUwukUlETBXulll3n826hOluxYi704',
        status: 'active',
        owner: 'Kevin',
        date: 'Yesterday'
    },
    {
        title: 'Daenerys POP Figurine',
        description: 'From season 5 so maybe you will still like her',
        condition: 'new',
        price: 30,
        city: 'Tempe',
        state: 'AZ',
        category: 'Misc',
        photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxKY0Aff-fD-IUM2ucI0iDiHiWLAx1qxzVnnnwwbz6R4OocZ3mPg',
        status: 'active',
        owner: 'Albee',
        date: 'Yesterday'
    },
    {
        title: 'Coffe Table',
        description: 'Its beautiful.',
        condition: 'new',
        price: 400,
        city: 'San Francisco',
        state: 'CA',
        category: 'Furniture',
        photo: 'https://i.imgur.com/JV5zBQ0.jpg',
        status: 'inactive',
        owner: 'Kevin',
        date: 'Yesterday'
    },
    {
        title: 'Roommate Wanted',
        description: 'I\'m cool I promise',
        condition: 'N/A',
        price: 400,
        city: 'Tempe',
        state: 'AZ',
        category: 'Living',
        photo: 'https://i.imgur.com/Sjt9XbS.jpg',
        status: 'active',
        owner: 'Liv',
        date: 'Yesterday'
    },
    {
        title: 'Puppy for Adoption',
        description: 'I mean come on!',
        condition: 'new',
        price: 400,
        city: 'Tempe',
        state: 'AZ',
        category: 'Pets',
        photo: 'https://i.imgur.com/A8eQsll.jpg',
        status: 'active',
        owner: 'Abhishek',
        date: 'Yesterday'
    },
]

export default data;